REGISTRATION_REPORT_LIMIT = 1000
OTHER_CITY_ID = 999999
OTHER_STATE_ID = 99999
MAX_ATTACHMENT_FILE_SIZE = 5.megabytes
RANDOM_PASSWORD_LENGTH = 8
FORUM_ATTENDANCE_EDITABLE_VALIDITY = 7
FORUM_ATTENDANCE_ALLOWED_EDIT_COUNT = 5
DEFAULT_RECORDS_PER_PAGE = 20
MAX_RECORDS_PER_PAGE = 100
PER_PAGE_OPTIONS = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
USER_ID_COOKIE_KEY = 'user_id'
NEW_SADHAK_PROFILE_COOKIE_KEY = 'new_sadhak_profile'
EDIT_SADHAK_PROFILE_ID_COOKIE_KEY = 'edit_sadhak_profile_id'
MEDIUM_TO_SEND_VERIFICATION_TOKEN = { 0 => "email", 1 => "mobile", 2 => "email and mobile" }
OAUTH_DATA = 'oauth_data'
NON_PROFESSIONAL_PROFESSIONS = ['Homemaker', 'Student', 'Unemployed']
DOCTOR = 'Doctor'
OAUTH_PARAM_SYIDS = 'syids'
SADHAK_MIN_AGE = 12
RESEND_TIMER_KEY = 'resend_timer'
RESEND_TIMER = 30
SADHAK_MAX_AGE = 110
DATA_SENDER_TYPE = ['bulk_sender', 'normal_sender']
REDIRECT_URL_COOKIE_KEY = 'redirect_url'
ASHRAM_RESIDENTIAL_SHIVIR_T_AND_C = ["I undertake that I'm not allergic to any food items. I shall happily accept food given to me during the shivir. (Please note no special food will be provided to anybody, satvic yogic food will be served during the shivir.)", "I undertake that I'm in sound physical and mental health to attend shivir.", "I undertake that during the shivir I'll not use cellphone", "I undertake that during the shivir I'll observe silence", "I undertake that I'll perform the sewa assigned to me", "I undertake that I shall report on the specified date and leave the ashram on the specified date and will not insist to leave the ashram in between", "I undertake that I am a believer of God and seek to awaken the Shiva consciousness within me", "I undertake that I'm grateful to shivyog guru Avdhoot Shivanand who is helping me to open the path of higher consciousness", "All the above information given by me are truthful", "I agree that the organization reserves the right to not accept my application and my stay in the ashram if found not truthful.", "With gratitude to God and the guru I write my name, it can be considered as my signature."]
ENCRYPT_PAYMENT_DETAILS_KEY = 'encrypt_payment_details'
OPTIONS_ACCEPTABLE_QUESTION_TYPES = %w(single_select multiple_select radio_button)
PREDEFINED_SADHAK_PROFILESTEPS = %w(basic_info professional_detail advance_profile spiritual_practice spiritual_journey self_reported name_of_guru other_spiritual_associations aspects_of_life sadhak_seva_preference medical_practitioners_profile special_other_infos)
QUESTION_FIELD_TYPES = %w(single_select multiple_select radio_button check_box text_area text_field date email)
ASHRAM_RESIDENTIAL_SHIVIR = 'Ashram Residential Shivirs'
SHIVIRS_1K = ["Shiv Yog Shambhavi(1K) Shivir", "Shiv Yog Sri Vidya(1K) Shivir"]
VALID_STATUSES = [Event.statuses.ready, Event.statuses.test_registration]
EVENT_ORDER_ACTIONS = { 0 => "transfer", 1 => "upgrade_downgrade", 2 => "cancel" }
EVENT_ORDER_LINE_ITEM_IDS = "event_order_line_item_ids"
SADHAK_PROFILE_DETAILS = "sadhak_profile_details"
PAYMENT_REFUND_PARAMS = 'request_params'
INDIA = "India"
SY_CONTENT_TYPE = {"Content in Hindi" => "Hindi", "Content in English" => "English", "Content in Bengali" => "Bengali", "Content in Other" => 'Other' }
SY_CLUB_DETAILS = "sy_club_details"
SY_CLUB_TRANSFER_DETAILS = "sy_club_transfer_details"
ISHAN_JI = "Ishan ji"
BABA_JI = "Baba ji"
SUBTLE_PRESENCE_OF_BABAJI = "Subtle presence of Babaji"
TERMS_AND_CONDITION_COMPANY = "Geetanjali Yog LLP - Delhi"
COMPLETE_PROFILE_REDIRECT_URL = "Complete profile redirect URL"
NO_SPECIAL_CHARACTER = /\A[A-Za-z0-9]+\Z/
ONLY_LETTER = /\A[a-zA-Z]+\z/
ONLY_LETTER_AND_SPACE = /\A[A-Za-z\s]+\z/
GRACED_BY_BABAJI = 'Baba ji'
STATE_DELHI = 'Delhi'
INTRASTATE = "Intrastate"
INTERSTATE = "Interstate"
RAKE_TASK_ARGS_SEPERATOR = '-'
ZERO_PAYMENT = "Zero Payment"
STATE_WITH_INVOICE_CODE = {"Andaman and Nicobar Islands" =>	{ tin_number: "35", code:	"AN"}, "Andhra Pradesh" => { tin_number: "37", code:	"AD"}, "Arunachal Pradesh" => { tin_number: "12", code:	"AR"}, "Assam" => { tin_number: "18" , code:	"AS"}, "Bihar" => { tin_number: "10" , code:	"BR"}, "Chandigarh" => { tin_number: "04" , code:	"CH"}, "Chhattisgarh" => { tin_number: "22" , code:	"CG"},		"Dadra and Nagar Haveli" => { tin_number: "26", code:	"DN"}, "Daman and Diu" => { tin_number: "25", code: "DD"}, "Delhi" => { tin_number:"07", code: "DL"}, "Goa" => { tin_number: "30", code: "GA"}, "Gujarat" => { tin_number: "24", code: "GJ"}, "Haryana" => { tin_number: "06", code: "HR"}, "Himachal Pradesh" => { tin_number: "02" , code: "HP"}, "Jammu and Kashmir	" => { tin_number: "01", code: "JK"},	"Jharkhand" => { tin_number: "20", code: "JH"}, "Karnataka" => { tin_number: "29", code: "KA"}, "Kerala" => { tin_number:"32", code:	"KL"}, "Lakshadweep Islands" => { tin_number: "31", code: "LD"}, "Madhya Pradesh" => { tin_number: "23", code:	"MP"}, "Maharashtra" => { tin_number: "27", code: "MH"}, "Manipur" => { tin_number: "14" , code:	"MN"}, "Meghalaya" => { tin_number: "17", code: "ML"}, "Mizoram" => { tin_number: "15", code: "MZ"}, "Nagaland" => { tin_number: "13" , code: "NL"}, "Odisha" => { tin_number: "21" , code: "OD"}, "Pondicherry" => { tin_number: "34", code: "PY"}, "Punjab" => { tin_number: "03", code:	"PB"}, "Rajasthan" => { tin_number: "08", code: "RJ"}, "Sikkim" => { tin_number: "11", code: "SK"}, "Tamil Nadu" => { tin_number: "33", code:	"TN"}, "Telangana" => { tin_number: "36", code: "TS"}, "Tripura" => { tin_number: "16" , code:	"TR"}, "Uttar Pradesh" => { tin_number: "09" , code: "UP"}, "Uttarakhand" => { tin_number: "05", code: "UK"	}, "West Bengal" => { tin_number: "19" , code:	"WB"}}
FORUM_TRANSFER_LIMIT = 3
QUESTIONNAIRE_MEDICINE_MODALITIES = ["none", "Pranic Healing", "Shiatsu", "Reiki", "Qigong", "Homeopathy", "Ayurveda", "Acupuncture", "Acupressure", "Magnet therapy","Therapeutic Touch therapy", "Others"]
QUESTIONNAIRE_SHIVIR_ATTENDED = ["Not Attended", "Siddha Healing", "Shambhavi", "Advait Sri Vidya 1, 2, 3", "Advait Sri Vidya 4", "Orientation", "Prati Prasav", "Art of Dying", "Art of self realization", "Siddha Scanning & Clairvoyance", "Cure is Possible", "Science Beyond Science", "Navagraha Sadhana", "Yoga of Immortals", "Crystal Healing", "others"]
