social:
  facebook: https://www.facebook.com/shivyogwisdom
  twitter: https://twitter.com/shivyoglive
  instagram: https://www.instagram.com/shiv_yog/
  youtube: https://www.youtube.com/user/shivyogchannel
  pinterest: https://www.pinterest.com/shivyoglive/
